# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
  host: db
  username: postgres
  password:
  pool: 5

local: 
  <<: *default
  
development:
  <<: *default
  database: rails-mister-cocktail_development

test:
  <<: *default
  database: rails-mister-cocktail_test

production:
  <<: *default
  database: rails-mister-cocktail_production
